# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_value', models.CharField(max_length=200)),
                ('second_value', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DetailsTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('path', models.CharField(max_length=350)),
                ('description', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_descr', models.CharField(max_length=350)),
                ('description', models.CharField(max_length=1000)),
                ('amount_of_photos', models.IntegerField(default=0)),
                ('created_on', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push_backend.Property'),
        ),
        migrations.AddField(
            model_name='detailstitle',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push_backend.Property'),
        ),
        migrations.AddField(
            model_name='details',
            name='detailsTitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push_backend.DetailsTitle'),
        ),
    ]
