# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='detailsTitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_values', to='push_backend.DetailsTitle'),
        ),
        migrations.AlterField(
            model_name='detailstitle',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_titles', to='push_backend.Property'),
        ),
        migrations.AlterField(
            model_name='image',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='push_backend.Property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(),
        ),
    ]
