# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_backend', '0002_auto_20170605_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_value', models.CharField(max_length=200)),
                ('second_value', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='details',
            name='detailsTitle',
        ),
        migrations.AlterField(
            model_name='detailstitle',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_titles', to='push_backend.Property'),
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.AddField(
            model_name='detail',
            name='detailsTitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='push_backend.DetailsTitle'),
        ),
    ]
