# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_backend', '0003_auto_20170605_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='detailsTitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_values', to='push_backend.DetailsTitle'),
        ),
        migrations.AlterField(
            model_name='detailstitle',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='push_backend.Property'),
        ),
    ]
